//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaratPrac14Entities1 : DbContext
    {
        public MaratPrac14Entities1()
            : base("name=MaratPrac14Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeRating> AgeRating { get; set; }
        public virtual DbSet<genres> genres { get; set; }
        public virtual DbSet<halls> halls { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<seats> seats { get; set; }
        public virtual DbSet<sessions> sessions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
