//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie_genres
    {
        public int movie_id { get; set; }
        public int genre_id { get; set; }
    
        public virtual genres genres { get; set; }
        public virtual Movies Movies { get; set; }
        public virtual Movies Movies1 { get; set; }
    }
}
