//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public int ticket_id { get; set; }
        public int user_id { get; set; }
        public int session_id { get; set; }
        public Nullable<System.DateTime> purchase_datetime { get; set; }
        public int hall_id { get; set; }
        public int seats_id { get; set; }
    
        public virtual halls halls { get; set; }
        public virtual sessions sessions { get; set; }
        public virtual users users { get; set; }
    }
}
